
# IMAGES #

# UI NAVIGATION #
img_addFriend = "add_friend.png"
img_allow = "allow.png"
img_allowFlash = "enableflash_0.png"
img_allowFlash1 = "enableflash_1.png"
img_allowFlash2 = "enableflash_2.png"
img_alreadyStarted = "alreadystarted.png"
img_alreadyStarted1 = "alreadystarted1.png"
img_backButton = "back_button.png"
img_challengeFriend = "challenge_friend.png"
img_cheapButtonFriend = "cheap_button_friend.png"
img_cheapButton = "cheap_button.png"
img_collectCoins = "collectcoins.png"
img_collectCoins1 = "collectcoins_1.png"
img_defaultAcct = "defaultaccount.png"
img_eightBallSpinButton = "8ballspin_button.png"
img_emailArea = "email_area.png"
img_facebookLogo = "facebooklogo.png"
img_inviteFriend = "invite_friend.png"
img_isGameStart = "isgamestart.png"
img_loginButton3 = "login3_button.png"
img_loginWithMiniclip = "login_with_miniclip.png"
img_mainMenuBefore = "mainmenu_before.png"
img_passwordArea = "password_area.png"
img_playButtonGuest = "play_button_guest.png"
img_playButtonLogged = "play_button_logged.png"
img_playFriends = "playfriends.png"
img_poolChoice = "poolchoice.png"
img_poolChoice1 = "poolchoice1.png"
img_poolChoice200 = "poolchoice200.png"
img_poolChoice200_1 = "poolchoice200_1.png"
img_searchFriends = "search_friends.png"
img_searchFriends1 = "search_friends2.png"
img_searchFriends2 = "search_friends3.png"
img_signUpLogin = "signup_login_button.png"
img_spinWinCollect = "spinwin_collect.png"
img_spinWinIcon = "spinwinicon.png"
img_spinWinX = "spinwin_x.png"
img_topRightCorner = "top_right_corner.png"
img_topRightCornerLogged = "top_right_corner_logged.png"
img_turn = "turn.png"
img_turn1 = "turn1.png"
img_url = "url.png"
img_url2 = "url2.png"
img_url3 = "url3.png"
img_urlBar = "urlbar.png"
img_unsecure = "unsecure.png"
img_xOut = "xout.png"
# UI NAVIGATION #

# GAME NAVIGATION #
img_1ball = "1ball.png"
img_2ball = "2ball.png"
img_3ball = "3ball.png"
img_4ball = "4ball.png"
img_5ball = "5ball.png"
img_6ball = "6ball.png"
img_7ball = "7ball.png"
img_8ball = "8ball.png"
img_9ball = "9ball.png"
img_10ball = "10ball.png"
img_11ball = "11ball.png"
img_12ball = "12ball.png"
img_13ball = "13ball.png"
img_14ball = "14ball.png"
img_15ball = "15ball.png"
img_cueball = "cueball.png"
img_eightball = "eightball.png"

img_ballPic1 = "ballpic1.png"

img_tlh = "tlh.png"
img_tmh = "tmh.png"
img_trh = "trh.png"
img_blh = "blh.png"
img_bmh = "bmh.png"
img_brh = "brh.png"

img_topRail = "toprail.png"
img_bottomRail = "bottomrail.png"
img_leftRail = "leftrail.png"
img_rightRail = "rightrail.png"
# GAME NAVIGATION #

# IMAGES #

debug = False